### ISSUE TITLE
Patch crashes game

### ISSUE THREAD

**Issue by celerizer** [SmartZero2025/ZombiU-Raytrace#1]
I moved the new files to content/lynfsatest/Shaders/ in my ZombiU install but it seems to crash the game on boot.

System: Wii U
Region: USA
Version: v32 with DLC

**Comment by SmartZero2025** [comment]
you have to use real WiiU hardware for this here...you know that? No emulator! and its for EUR version here only. No DLC support!

no modern homebrew support!

**Comment by celerizer** [comment]
I'm using my real Wii U. I'll try again with the European version when I find a chance. Thank you.
